### ISSUE TITLE
"Error: Cannot call a namespace ('getISOWeek')"  ionic 2 - rc0

### ISSUE THREAD

**Issue by bilalyilmax** [mattlewis92/angular2-calendar#67]
I get the following error when running ionic serve.. 
 Any help resolving this issue would be greatly appreciated.

```
$ ionic serve
Running 'serve:before' npm script before serve
> ionic-hello-world@ watch E:\web\apps\femkoApp
> ionic-app-scripts watch
[15:34:57]  ionic-app-scripts 0.0.23
[15:34:57]  watch started ...
[15:34:57]  build dev started ...
[15:34:57]  clean started ...
[15:34:57]  clean finished in 14 ms
[15:34:57]  copy started ...
[15:34:57]  typescript compiler started ...
[15:34:57]  lint started ...
[15:34:57]  copy finished in 86 ms
[15:34:58]  lint finished in 899 ms
[15:35:01]  typescript compiler ready in 4.44 s
[15:35:01]  bundle dev started ...
[15:35:07]  Error: Cannot call a namespace ('getISOWeek')
    at error (E:\web\apps\femkoApp\node_modules\rollup\dist\rollup.js:5406:12)
    at CallExpression.bind (E:\web\apps\femkoApp\node_modules\rollup\dist\rollup.js:5829:5)
    at E:\web\apps\femkoApp\node_modules\rollup\dist\rollup.js:5151:50
    at VariableDeclarator.eachChild (E:\web\apps\femkoApp\node_modules\rollup\dist\rollup.js:5168:5)
    at VariableDeclarator.bind (E:\web\apps\femkoApp\node_modules\rollup\dist\rollup.js:5151:7)
    at E:\web\apps\femkoApp\node_modules\rollup\dist\rollup.js:5151:50
    at VariableDeclaration.eachChild (E:\web\apps\femkoApp\node_modules\rollup\dist\rollup.js:5165:19)
    at VariableDeclaration.bind (E:\web\apps\femkoApp\node_modules\rollup\dist\rollup.js:5151:7)
    at BlockStatement.bind (E:\web\apps\femkoApp\node_modules\rollup\dist\rollup.js:5617:9)
    at FunctionExpression.bind (E:\web\apps\femkoApp\node_modules\rollup\dist\rollup.js:6458:13)

[15:35:07]  sass started ...
[15:35:09]  sass finished in 1.67 s
[15:35:09]  build dev finished in 12.10 s
[15:35:09]  watch ready in 12.18 s
```

**app.module.ts**
```
import { NgModule } from '@angular/core';
import { IonicApp, IonicModule } from 'ionic-angular';
import { BrowserModule } from '@angular/platform-browser';
import { MyApp } from './app.component';
import { Page1 } from '../pages/page1/page1';
import { Page2 } from '../pages/page2/page2';
import { HttpModule } from '@angular/http';
import { provideAuth, AuthHttp } from 'angular2-jwt';
import { CalendarModule, CalendarEventTitle, CalendarDateFormatter } from 'angular2-calendar';

@NgModule({
  declarations: [
    MyApp,
    Page1,
    Page2
  ],
  imports: [
    IonicModule.forRoot(MyApp),
    HttpModule,
    BrowserModule, CalendarModule

  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    Page1,
    Page2
  ],
  providers: [
    AuthHttp,
    provideAuth({
      headerName: 'authorization',
      headerPrefix: 'Bearer',
      tokenName: 'token',
      tokenGetter: (() => localStorage.getItem('id_token')),
      globalHeaders: [{ 'Content-Type': 'application/json' }],
      noJwtError: true
    }),
    CalendarEventTitle,
    CalendarDateFormatter
  ]
})
export class AppModule {}
```
**page1.ts**
```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

import { AuthHttp } from 'angular2-jwt';
import { startOfDay, subDays, addDays, endOfMonth, isSameDay, isSameMonth, addWeeks, subWeeks, addMonths, subMonths } from 'date-fns';
import { CalendarEvent, CalendarEventAction } from "angular2-calendar"


const colors: any = {
  red: { primary: '#ad2121', secondary: '#FAE3E3' },
  blue: { primary: '#1e90ff', secondary: '#D1E8FF' },
  yellow: { primary: '#e3bc08', secondary: '#FDF1BA' }
};


@Component({
  selector: 'page-page1',
  templateUrl: 'page1.html',
})
export class Page1 {

  view: string = 'month';

  viewDate: Date = new Date();

  actions: CalendarEventAction[] = [{
    label: '<i class="fa fa-fw fa-pencil"></i>',
    onClick: ({event}: {event: CalendarEvent}): void => {
      console.log('Edit event', event);
    }
  }, {
    label: '<i class="fa fa-fw fa-times"></i>',
    onClick: ({event}: {event: CalendarEvent}): void => {
      this.events = this.events.filter(iEvent => iEvent !== event);
    }
  }];

  events: CalendarEvent[] = [{
    start: subDays(startOfDay(new Date()), 1),
    end: addDays(new Date(), 1),
    title: 'A 3 day event',
    color: colors.red,
    actions: this.actions
  }, {
    start: startOfDay(new Date()),
    title: 'An event with no end date',
    color: colors.yellow,
    actions: this.actions
  }, {
    start: subDays(endOfMonth(new Date()), 3),
    end: addDays(endOfMonth(new Date()), 3),
    title: 'A long event that spans 2 months',
    color: colors.blue
  }];

  activeDayIsOpen: boolean = true;

  increment(): void {

    const addFn: any = {
      day: addDays,
      week: addWeeks,
      month: addMonths
    }[this.view];

    this.viewDate = addFn(this.viewDate, 1);

  }

  decrement(): void {

    const subFn: any = {
      day: subDays,
      week: subWeeks,
      month: subMonths
    }[this.view];

    this.viewDate = subFn(this.viewDate, 1);

  }

  today(): void {
    this.viewDate = new Date();
  }

  dayClicked({date, events}: {date: Date, events: CalendarEvent[]}): void {

    if (isSameMonth(date, this.viewDate)) {
      if (
        (isSameDay(this.viewDate, date) && this.activeDayIsOpen === true) ||
        events.length === 0
      ) {
        this.activeDayIsOpen = false;
      } else {
        this.activeDayIsOpen = true;
        this.viewDate = date;
      }
    }
  }


}
```

**page1.html**
```

<ion-content padding>



  <div class="container">
      <div class="row text-center">
        <div class="col-md-4">
           <div class="btn-group">
             <div class="btn btn-primary" (click)="decrement()">
               Previous
             </div>
             <div class="btn btn-default" (click)="today()">
               Today
             </div>
             <div class="btn btn-primary" (click)="increment()">
               Next
             </div>
           </div>
        </div>
        <div class="col-md-4">
          <h3>{{ viewDate | calendarDate:(view + 'ViewTitle'):'en' }}</h3>
        </div>
        <div class="col-md-4">
          <div class="btn-group">
            <div class="btn btn-primary" (click)="view = 'month'" [class.active]="view === 'month'">Month</div>
            <div class="btn btn-primary" (click)="view = 'week'" [class.active]="view === 'week'">Week</div>
            <div class="btn btn-primary" (click)="view = 'day'" [class.active]="view === 'day'">Day</div>
          </div>
        </div>
      </div>
      <br>
      <div [ngSwitch]="view">
        <mwl-calendar-month-view
          *ngSwitchCase="'month'"
          [viewDate]="viewDate"
          [events]="events"
          [activeDayIsOpen]="activeDayIsOpen"
          (dayClicked)="dayClicked($event.day)">
        </mwl-calendar-month-view>
        <mwl-calendar-week-view
          *ngSwitchCase="'week'"
          [viewDate]="viewDate"
          [events]="events">
        </mwl-calendar-week-view>
        <mwl-calendar-day-view
          *ngSwitchCase="'day'"
          [viewDate]="viewDate"
          [events]="events">
        </mwl-calendar-day-view>
      </div>
    </div>

</ion-content>

```

**Comment by mattlewis92** [comment]
I've hit this issue before, it's because of a conflict between the way that rollup and typescript treat commonjs / ES6 modules interop. Typescript expects `import * as lib from 'lib';` to import the value from `module.exports` and rollup expects `import lib from 'lib';` to import the value from `module.exports`. Googling about reveals that there is no easy way to get them to play together, I think the easiest way to solve this is just to go back to commonjs `requires` for the `date-fns` lib. I will cut a new release tonight that should solve the issue. 

ps I wouldn't recommend using this in ionic as it's not very responsive, this might suit your needs better: https://github.com/twinssbc/Ionic2-Calendar

**Comment by mattlewis92** [comment]
Should be fixed in https://github.com/mattlewis92/angular2-calendar/commit/7e758badf6a2d064dae0dadf5120bdb132cf05ff and released as `0.2.7`, thanks for reporting! 😄

**Comment by bilalyilmax** [comment]
I'm new for mobile software
There is much to learn
Thanks you for the help

**Comment by mattlewis92** [comment]
No problem 😀
